---
- name: packages | apt | update cache
  apt:
    update_cache: yes

- name: packages | apt | add/remove packages
  apt:
    name: {{ item.name }}
    state: {{ item.state | default("present") }}
  with_items: packages
